// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vatest_proto.proto

package edu.psu.cse.vatest;

public final class VatestProto {
  private VatestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vatest_proto.ServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .vatest_proto.ServerMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .vatest_proto.ServerMessage.Type type = 1;</code>
     */
    edu.psu.cse.vatest.VatestProto.ServerMessage.Type getType();

    /**
     * <code>optional string path = 2;</code>
     */
    boolean hasPath();
    /**
     * <code>optional string path = 2;</code>
     */
    java.lang.String getPath();
    /**
     * <code>optional string path = 2;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>repeated uint32 tags = 3;</code>
     */
    java.util.List<java.lang.Integer> getTagsList();
    /**
     * <code>repeated uint32 tags = 3;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated uint32 tags = 3;</code>
     */
    int getTags(int index);

    /**
     * <code>optional uint32 batch = 4;</code>
     */
    boolean hasBatch();
    /**
     * <code>optional uint32 batch = 4;</code>
     */
    int getBatch();

    /**
     * <code>repeated uint64 size = 5;</code>
     */
    java.util.List<java.lang.Long> getSizeList();
    /**
     * <code>repeated uint64 size = 5;</code>
     */
    int getSizeCount();
    /**
     * <code>repeated uint64 size = 5;</code>
     */
    long getSize(int index);
  }
  /**
   * Protobuf type {@code vatest_proto.ServerMessage}
   */
  public static final class ServerMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vatest_proto.ServerMessage)
      ServerMessageOrBuilder {
    // Use ServerMessage.newBuilder() to construct.
    private ServerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerMessage defaultInstance;
    public static ServerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ServerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.psu.cse.vatest.VatestProto.ServerMessage.Type value = edu.psu.cse.vatest.VatestProto.ServerMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              path_ = bs;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                tags_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              tags_.add(input.readUInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                tags_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                tags_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              batch_ = input.readUInt32();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                size_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              size_.add(input.readUInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                size_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                size_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          size_ = java.util.Collections.unmodifiableList(size_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.psu.cse.vatest.VatestProto.ServerMessage.class, edu.psu.cse.vatest.VatestProto.ServerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerMessage> PARSER =
        new com.google.protobuf.AbstractParser<ServerMessage>() {
      public ServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code vatest_proto.ServerMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONNECT = 0;</code>
       */
      CONNECT(0, 0),
      /**
       * <code>VIDEO = 1;</code>
       */
      VIDEO(1, 1),
      /**
       * <code>BATCH = 2;</code>
       */
      BATCH(2, 2),
      /**
       * <code>DISCONNECT = 3;</code>
       */
      DISCONNECT(3, 3),
      ;

      /**
       * <code>CONNECT = 0;</code>
       */
      public static final int CONNECT_VALUE = 0;
      /**
       * <code>VIDEO = 1;</code>
       */
      public static final int VIDEO_VALUE = 1;
      /**
       * <code>BATCH = 2;</code>
       */
      public static final int BATCH_VALUE = 2;
      /**
       * <code>DISCONNECT = 3;</code>
       */
      public static final int DISCONNECT_VALUE = 3;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return CONNECT;
          case 1: return VIDEO;
          case 2: return BATCH;
          case 3: return DISCONNECT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.psu.cse.vatest.VatestProto.ServerMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:vatest_proto.ServerMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.psu.cse.vatest.VatestProto.ServerMessage.Type type_;
    /**
     * <code>required .vatest_proto.ServerMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .vatest_proto.ServerMessage.Type type = 1;</code>
     */
    public edu.psu.cse.vatest.VatestProto.ServerMessage.Type getType() {
      return type_;
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private java.lang.Object path_;
    /**
     * <code>optional string path = 2;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string path = 2;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string path = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> tags_;
    /**
     * <code>repeated uint32 tags = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated uint32 tags = 3;</code>
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated uint32 tags = 3;</code>
     */
    public int getTags(int index) {
      return tags_.get(index);
    }

    public static final int BATCH_FIELD_NUMBER = 4;
    private int batch_;
    /**
     * <code>optional uint32 batch = 4;</code>
     */
    public boolean hasBatch() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 batch = 4;</code>
     */
    public int getBatch() {
      return batch_;
    }

    public static final int SIZE_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> size_;
    /**
     * <code>repeated uint64 size = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getSizeList() {
      return size_;
    }
    /**
     * <code>repeated uint64 size = 5;</code>
     */
    public int getSizeCount() {
      return size_.size();
    }
    /**
     * <code>repeated uint64 size = 5;</code>
     */
    public long getSize(int index) {
      return size_.get(index);
    }

    private void initFields() {
      type_ = edu.psu.cse.vatest.VatestProto.ServerMessage.Type.CONNECT;
      path_ = "";
      tags_ = java.util.Collections.emptyList();
      batch_ = 0;
      size_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPathBytes());
      }
      for (int i = 0; i < tags_.size(); i++) {
        output.writeUInt32(3, tags_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, batch_);
      }
      for (int i = 0; i < size_.size(); i++) {
        output.writeUInt64(5, size_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPathBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tags_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(tags_.get(i));
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, batch_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < size_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(size_.get(i));
        }
        size += dataSize;
        size += 1 * getSizeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.psu.cse.vatest.VatestProto.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.psu.cse.vatest.VatestProto.ServerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vatest_proto.ServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vatest_proto.ServerMessage)
        edu.psu.cse.vatest.VatestProto.ServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.psu.cse.vatest.VatestProto.ServerMessage.class, edu.psu.cse.vatest.VatestProto.ServerMessage.Builder.class);
      }

      // Construct using edu.psu.cse.vatest.VatestProto.ServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = edu.psu.cse.vatest.VatestProto.ServerMessage.Type.CONNECT;
        bitField0_ = (bitField0_ & ~0x00000001);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        batch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        size_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ServerMessage_descriptor;
      }

      public edu.psu.cse.vatest.VatestProto.ServerMessage getDefaultInstanceForType() {
        return edu.psu.cse.vatest.VatestProto.ServerMessage.getDefaultInstance();
      }

      public edu.psu.cse.vatest.VatestProto.ServerMessage build() {
        edu.psu.cse.vatest.VatestProto.ServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.psu.cse.vatest.VatestProto.ServerMessage buildPartial() {
        edu.psu.cse.vatest.VatestProto.ServerMessage result = new edu.psu.cse.vatest.VatestProto.ServerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.path_ = path_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tags_ = tags_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.batch_ = batch_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size_ = java.util.Collections.unmodifiableList(size_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.psu.cse.vatest.VatestProto.ServerMessage) {
          return mergeFrom((edu.psu.cse.vatest.VatestProto.ServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.psu.cse.vatest.VatestProto.ServerMessage other) {
        if (other == edu.psu.cse.vatest.VatestProto.ServerMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000002;
          path_ = other.path_;
          onChanged();
        }
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
        if (other.hasBatch()) {
          setBatch(other.getBatch());
        }
        if (!other.size_.isEmpty()) {
          if (size_.isEmpty()) {
            size_ = other.size_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSizeIsMutable();
            size_.addAll(other.size_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.psu.cse.vatest.VatestProto.ServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.psu.cse.vatest.VatestProto.ServerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private edu.psu.cse.vatest.VatestProto.ServerMessage.Type type_ = edu.psu.cse.vatest.VatestProto.ServerMessage.Type.CONNECT;
      /**
       * <code>required .vatest_proto.ServerMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .vatest_proto.ServerMessage.Type type = 1;</code>
       */
      public edu.psu.cse.vatest.VatestProto.ServerMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .vatest_proto.ServerMessage.Type type = 1;</code>
       */
      public Builder setType(edu.psu.cse.vatest.VatestProto.ServerMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .vatest_proto.ServerMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.psu.cse.vatest.VatestProto.ServerMessage.Type.CONNECT;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>optional string path = 2;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            path_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        path_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> tags_ = java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          tags_ = new java.util.ArrayList<java.lang.Integer>(tags_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated uint32 tags = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getTagsList() {
        return java.util.Collections.unmodifiableList(tags_);
      }
      /**
       * <code>repeated uint32 tags = 3;</code>
       */
      public int getTagsCount() {
        return tags_.size();
      }
      /**
       * <code>repeated uint32 tags = 3;</code>
       */
      public int getTags(int index) {
        return tags_.get(index);
      }
      /**
       * <code>repeated uint32 tags = 3;</code>
       */
      public Builder setTags(
          int index, int value) {
        ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tags = 3;</code>
       */
      public Builder addTags(int value) {
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tags = 3;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tags = 3;</code>
       */
      public Builder clearTags() {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private int batch_ ;
      /**
       * <code>optional uint32 batch = 4;</code>
       */
      public boolean hasBatch() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 batch = 4;</code>
       */
      public int getBatch() {
        return batch_;
      }
      /**
       * <code>optional uint32 batch = 4;</code>
       */
      public Builder setBatch(int value) {
        bitField0_ |= 0x00000008;
        batch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 batch = 4;</code>
       */
      public Builder clearBatch() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batch_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> size_ = java.util.Collections.emptyList();
      private void ensureSizeIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          size_ = new java.util.ArrayList<java.lang.Long>(size_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated uint64 size = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getSizeList() {
        return java.util.Collections.unmodifiableList(size_);
      }
      /**
       * <code>repeated uint64 size = 5;</code>
       */
      public int getSizeCount() {
        return size_.size();
      }
      /**
       * <code>repeated uint64 size = 5;</code>
       */
      public long getSize(int index) {
        return size_.get(index);
      }
      /**
       * <code>repeated uint64 size = 5;</code>
       */
      public Builder setSize(
          int index, long value) {
        ensureSizeIsMutable();
        size_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 size = 5;</code>
       */
      public Builder addSize(long value) {
        ensureSizeIsMutable();
        size_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 size = 5;</code>
       */
      public Builder addAllSize(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSizeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, size_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 size = 5;</code>
       */
      public Builder clearSize() {
        size_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vatest_proto.ServerMessage)
    }

    static {
      defaultInstance = new ServerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:vatest_proto.ServerMessage)
  }

  public interface ClientMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vatest_proto.ClientMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .vatest_proto.ClientMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .vatest_proto.ClientMessage.Type type = 1;</code>
     */
    edu.psu.cse.vatest.VatestProto.ClientMessage.Type getType();

    /**
     * <code>optional string path = 2;</code>
     */
    boolean hasPath();
    /**
     * <code>optional string path = 2;</code>
     */
    java.lang.String getPath();
    /**
     * <code>optional string path = 2;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>repeated uint64 size = 3;</code>
     */
    java.util.List<java.lang.Long> getSizeList();
    /**
     * <code>repeated uint64 size = 3;</code>
     */
    int getSizeCount();
    /**
     * <code>repeated uint64 size = 3;</code>
     */
    long getSize(int index);

    /**
     * <code>optional uint32 batch = 4;</code>
     */
    boolean hasBatch();
    /**
     * <code>optional uint32 batch = 4;</code>
     */
    int getBatch();

    /**
     * <code>optional uint32 top_k = 5;</code>
     */
    boolean hasTopK();
    /**
     * <code>optional uint32 top_k = 5;</code>
     */
    int getTopK();
  }
  /**
   * Protobuf type {@code vatest_proto.ClientMessage}
   */
  public static final class ClientMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vatest_proto.ClientMessage)
      ClientMessageOrBuilder {
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientMessage defaultInstance;
    public static ClientMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ClientMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.psu.cse.vatest.VatestProto.ClientMessage.Type value = edu.psu.cse.vatest.VatestProto.ClientMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              path_ = bs;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                size_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              size_.add(input.readUInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                size_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                size_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              batch_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              topK_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          size_ = java.util.Collections.unmodifiableList(size_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ClientMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.psu.cse.vatest.VatestProto.ClientMessage.class, edu.psu.cse.vatest.VatestProto.ClientMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientMessage> PARSER =
        new com.google.protobuf.AbstractParser<ClientMessage>() {
      public ClientMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code vatest_proto.ClientMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONNECT = 0;</code>
       */
      CONNECT(0, 0),
      /**
       * <code>VIDEO = 1;</code>
       */
      VIDEO(1, 1),
      /**
       * <code>FRAME = 2;</code>
       */
      FRAME(2, 2),
      /**
       * <code>BATCH = 3;</code>
       */
      BATCH(3, 3),
      /**
       * <code>UPLINK_TEST = 4;</code>
       */
      UPLINK_TEST(4, 4),
      /**
       * <code>DISCONNECT = 5;</code>
       */
      DISCONNECT(5, 5),
      ;

      /**
       * <code>CONNECT = 0;</code>
       */
      public static final int CONNECT_VALUE = 0;
      /**
       * <code>VIDEO = 1;</code>
       */
      public static final int VIDEO_VALUE = 1;
      /**
       * <code>FRAME = 2;</code>
       */
      public static final int FRAME_VALUE = 2;
      /**
       * <code>BATCH = 3;</code>
       */
      public static final int BATCH_VALUE = 3;
      /**
       * <code>UPLINK_TEST = 4;</code>
       */
      public static final int UPLINK_TEST_VALUE = 4;
      /**
       * <code>DISCONNECT = 5;</code>
       */
      public static final int DISCONNECT_VALUE = 5;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return CONNECT;
          case 1: return VIDEO;
          case 2: return FRAME;
          case 3: return BATCH;
          case 4: return UPLINK_TEST;
          case 5: return DISCONNECT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.psu.cse.vatest.VatestProto.ClientMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:vatest_proto.ClientMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.psu.cse.vatest.VatestProto.ClientMessage.Type type_;
    /**
     * <code>required .vatest_proto.ClientMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .vatest_proto.ClientMessage.Type type = 1;</code>
     */
    public edu.psu.cse.vatest.VatestProto.ClientMessage.Type getType() {
      return type_;
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private java.lang.Object path_;
    /**
     * <code>optional string path = 2;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string path = 2;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string path = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> size_;
    /**
     * <code>repeated uint64 size = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getSizeList() {
      return size_;
    }
    /**
     * <code>repeated uint64 size = 3;</code>
     */
    public int getSizeCount() {
      return size_.size();
    }
    /**
     * <code>repeated uint64 size = 3;</code>
     */
    public long getSize(int index) {
      return size_.get(index);
    }

    public static final int BATCH_FIELD_NUMBER = 4;
    private int batch_;
    /**
     * <code>optional uint32 batch = 4;</code>
     */
    public boolean hasBatch() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 batch = 4;</code>
     */
    public int getBatch() {
      return batch_;
    }

    public static final int TOP_K_FIELD_NUMBER = 5;
    private int topK_;
    /**
     * <code>optional uint32 top_k = 5;</code>
     */
    public boolean hasTopK() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 top_k = 5;</code>
     */
    public int getTopK() {
      return topK_;
    }

    private void initFields() {
      type_ = edu.psu.cse.vatest.VatestProto.ClientMessage.Type.CONNECT;
      path_ = "";
      size_ = java.util.Collections.emptyList();
      batch_ = 0;
      topK_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPathBytes());
      }
      for (int i = 0; i < size_.size(); i++) {
        output.writeUInt64(3, size_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, batch_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(5, topK_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPathBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < size_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(size_.get(i));
        }
        size += dataSize;
        size += 1 * getSizeList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, batch_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, topK_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.psu.cse.vatest.VatestProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.psu.cse.vatest.VatestProto.ClientMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vatest_proto.ClientMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vatest_proto.ClientMessage)
        edu.psu.cse.vatest.VatestProto.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ClientMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ClientMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.psu.cse.vatest.VatestProto.ClientMessage.class, edu.psu.cse.vatest.VatestProto.ClientMessage.Builder.class);
      }

      // Construct using edu.psu.cse.vatest.VatestProto.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = edu.psu.cse.vatest.VatestProto.ClientMessage.Type.CONNECT;
        bitField0_ = (bitField0_ & ~0x00000001);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        batch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        topK_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.psu.cse.vatest.VatestProto.internal_static_vatest_proto_ClientMessage_descriptor;
      }

      public edu.psu.cse.vatest.VatestProto.ClientMessage getDefaultInstanceForType() {
        return edu.psu.cse.vatest.VatestProto.ClientMessage.getDefaultInstance();
      }

      public edu.psu.cse.vatest.VatestProto.ClientMessage build() {
        edu.psu.cse.vatest.VatestProto.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.psu.cse.vatest.VatestProto.ClientMessage buildPartial() {
        edu.psu.cse.vatest.VatestProto.ClientMessage result = new edu.psu.cse.vatest.VatestProto.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.path_ = path_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size_ = java.util.Collections.unmodifiableList(size_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.batch_ = batch_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.topK_ = topK_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.psu.cse.vatest.VatestProto.ClientMessage) {
          return mergeFrom((edu.psu.cse.vatest.VatestProto.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.psu.cse.vatest.VatestProto.ClientMessage other) {
        if (other == edu.psu.cse.vatest.VatestProto.ClientMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000002;
          path_ = other.path_;
          onChanged();
        }
        if (!other.size_.isEmpty()) {
          if (size_.isEmpty()) {
            size_ = other.size_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSizeIsMutable();
            size_.addAll(other.size_);
          }
          onChanged();
        }
        if (other.hasBatch()) {
          setBatch(other.getBatch());
        }
        if (other.hasTopK()) {
          setTopK(other.getTopK());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.psu.cse.vatest.VatestProto.ClientMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.psu.cse.vatest.VatestProto.ClientMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private edu.psu.cse.vatest.VatestProto.ClientMessage.Type type_ = edu.psu.cse.vatest.VatestProto.ClientMessage.Type.CONNECT;
      /**
       * <code>required .vatest_proto.ClientMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .vatest_proto.ClientMessage.Type type = 1;</code>
       */
      public edu.psu.cse.vatest.VatestProto.ClientMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .vatest_proto.ClientMessage.Type type = 1;</code>
       */
      public Builder setType(edu.psu.cse.vatest.VatestProto.ClientMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .vatest_proto.ClientMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.psu.cse.vatest.VatestProto.ClientMessage.Type.CONNECT;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>optional string path = 2;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            path_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 2;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        path_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> size_ = java.util.Collections.emptyList();
      private void ensureSizeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          size_ = new java.util.ArrayList<java.lang.Long>(size_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated uint64 size = 3;</code>
       */
      public java.util.List<java.lang.Long>
          getSizeList() {
        return java.util.Collections.unmodifiableList(size_);
      }
      /**
       * <code>repeated uint64 size = 3;</code>
       */
      public int getSizeCount() {
        return size_.size();
      }
      /**
       * <code>repeated uint64 size = 3;</code>
       */
      public long getSize(int index) {
        return size_.get(index);
      }
      /**
       * <code>repeated uint64 size = 3;</code>
       */
      public Builder setSize(
          int index, long value) {
        ensureSizeIsMutable();
        size_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 size = 3;</code>
       */
      public Builder addSize(long value) {
        ensureSizeIsMutable();
        size_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 size = 3;</code>
       */
      public Builder addAllSize(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSizeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, size_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 size = 3;</code>
       */
      public Builder clearSize() {
        size_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private int batch_ ;
      /**
       * <code>optional uint32 batch = 4;</code>
       */
      public boolean hasBatch() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 batch = 4;</code>
       */
      public int getBatch() {
        return batch_;
      }
      /**
       * <code>optional uint32 batch = 4;</code>
       */
      public Builder setBatch(int value) {
        bitField0_ |= 0x00000008;
        batch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 batch = 4;</code>
       */
      public Builder clearBatch() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batch_ = 0;
        onChanged();
        return this;
      }

      private int topK_ ;
      /**
       * <code>optional uint32 top_k = 5;</code>
       */
      public boolean hasTopK() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 top_k = 5;</code>
       */
      public int getTopK() {
        return topK_;
      }
      /**
       * <code>optional uint32 top_k = 5;</code>
       */
      public Builder setTopK(int value) {
        bitField0_ |= 0x00000010;
        topK_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 top_k = 5;</code>
       */
      public Builder clearTopK() {
        bitField0_ = (bitField0_ & ~0x00000010);
        topK_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vatest_proto.ClientMessage)
    }

    static {
      defaultInstance = new ClientMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:vatest_proto.ClientMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vatest_proto_ServerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vatest_proto_ServerMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vatest_proto_ClientMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vatest_proto_ClientMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022vatest_proto.proto\022\014vatest_proto\"\263\001\n\rS" +
      "erverMessage\022.\n\004type\030\001 \002(\0162 .vatest_prot" +
      "o.ServerMessage.Type\022\014\n\004path\030\002 \001(\t\022\014\n\004ta" +
      "gs\030\003 \003(\r\022\r\n\005batch\030\004 \001(\r\022\014\n\004size\030\005 \003(\004\"9\n" +
      "\004Type\022\013\n\007CONNECT\020\000\022\t\n\005VIDEO\020\001\022\t\n\005BATCH\020\002" +
      "\022\016\n\nDISCONNECT\020\003\"\320\001\n\rClientMessage\022.\n\004ty" +
      "pe\030\001 \002(\0162 .vatest_proto.ClientMessage.Ty" +
      "pe\022\014\n\004path\030\002 \001(\t\022\014\n\004size\030\003 \003(\004\022\r\n\005batch\030" +
      "\004 \001(\r\022\r\n\005top_k\030\005 \001(\r\"U\n\004Type\022\013\n\007CONNECT\020" +
      "\000\022\t\n\005VIDEO\020\001\022\t\n\005FRAME\020\002\022\t\n\005BATCH\020\003\022\017\n\013UP",
      "LINK_TEST\020\004\022\016\n\nDISCONNECT\020\005B\024\n\022edu.psu.c" +
      "se.vatest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vatest_proto_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vatest_proto_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vatest_proto_ServerMessage_descriptor,
        new java.lang.String[] { "Type", "Path", "Tags", "Batch", "Size", });
    internal_static_vatest_proto_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vatest_proto_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vatest_proto_ClientMessage_descriptor,
        new java.lang.String[] { "Type", "Path", "Size", "Batch", "TopK", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
